name: kaze

services:
  postgres:
    image: postgres:16-alpine
    container_name: kaze-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kaze
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: kaze-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redis_data:/data

  adminer:
    image: adminer:latest
    container_name: kaze-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
